site_name: Coding Geeks
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - content.code.copy

# Page tree
nav:
  - Home: index.md
  - Data structure:
    - index/data-structure/index.md
    - List: 
      - index/list/index.md
    - Linked list: data-structure/data-structure-linked-list.md
    - Stack: data-structure/data-structure-stack.md
    - Queue: data-structure/data-structure-queue.md
    - Deque: data-structure/data-structure-deque.md
    - LRU cache: data-structure/data-structure-lru-cache.md
    - LFU cache: data-structure/data-structure-lfu-cache.md
    - Monotonic queue: data-structure/data-structure-monotonic-queue.md
    - Skip list: data-structure/data-structure-skip-list.md
    - Tree: 
      - index/tree/index.md
      - Binary tree: data-structure/data-structure-binary-tree.md
      - Binary search tree: data-structure/data-structure-binary-search-tree.md
      - Red black tree: data-structure/data-structure-red-black-tree.md
      - N-ary tree: data-structure/data-structure-nary-tree.md
      - B tree: data-structure/data-structure-b-tree.md
      - B+ tree: data-structure/data-structure-b-plus-tree.md
      - Trie: data-structure/data-structure-trie.md
      - Segment tree: data-structure/data-structure-segment-tree.md
      - Fenwick tree: data-structure/data-structure-fenwick-tree.md
    - Set and map: 
      - index/map/index.md
      - HashMap: data-structure/data-structure-hashmap.md
      - Heap: data-structure/data-structure-heap.md
      - Bloom filter: data-structure/data-structure-bloom-filter.md
    - Graph: 
      - index/graph/index.md
      - Graph: data-structure/data-structure-graph.md
      #- Graph Problems: data-structure/data-structure-graph-problems.md
      - Bipartite graph: data-structure/data-structure-bipartite-graph.md
      - Directed graph: data-structure/data-structure-directed-graph.md
      - Topological sorting: data-structure/data-structure-topological-sorting.md
      - Minimum spanning tree: data-structure/data-structure-minimum-spanning-tree.md
  - Algorithm:
    - index/algorithm/index.md
    - Sorting:
      - index/sorting/index.md
      - Basic sorting algorithms: algorithm/algorithm-sorting.md
      - Heap sort: algorithm/algorithm-sorting.md
      - Merge sort: algorithm/algorithm-sorting.md
      - Quick sort: algorithm/algorithm-sorting.md
      - Bucket sort: algorithm/algorithm-sorting.md
    - Common algorithms:
      #- index/commons/index.md
      - Binary search: algorithm/algorithm-binary-search.md
      - Divide and conquer: algorithm/algorithm-divide-and-conquer.md
      - BFS and DFS: algorithm/algorithm-bfs-and-dfs.md
      - Two pointers: algorithm/algorithm-two-pointers.md
      - Combination and permutation: algorithm/algorithm-combination-and-permutation.md
      - Union find: algorithm/algorithm-union-find.md
    - Dynamic programming:
      - index/dp/index.md
      - Dynamic programming: algorithm/algorithm-dynamic-programming.md
      - Sequence DP: algorithm/algorithm-sequence-dp.md
      - Two sequences DP: algorithm/algorithm-two-sequences-dp.md
      - Matrix DP: algorithm/algorithm-matrix-dp.md
      - Knapsack problems: algorithm/algorithm-knapsack-problems.md
    - Other Algorithms:
      #- index/other/index.md
      - Sweep line: algorithm/algorithm-sweep-line.md
      - Sqrt decomposition: algorithm/algorithm-sqrt-decomposition.md
      - Minimax algorithm: algorithm/algorithm-minimax-algorithm.md
      - Map reduce: algorithm/algorithm-map-reduce.md
      - Pre sum: algorithm/algorithm-pre-sum.md
      - Coordinate: algorithm/algorithm-coordinate.md
      - Bit manipulation: algorithm/algorithm-bit-manipulation.md
      - Math: algorithm/algorithm-math.md
      - Random: algorithm/algorithm-random.md
  - Design pattern:
    - index/design-pattern/index.md
    - Creational Pattern:
      - Singleton: design-pattern/design-pattern-singleton.md
      - Factory: design-pattern/design-pattern-factory.md
      - Builder: design-pattern/design-pattern-builder.md
      - Prototype: design-pattern/design-pattern-prototype.md
      - DTO: design-pattern/design-pattern-dto.md
    - Structural Pattern:
      - Adapter: design-pattern/design-pattern-adapter.md
      - Bridge: design-pattern/design-pattern-bridge.md
      - Composite: design-pattern/design-pattern-composite.md
      - Decorator: design-pattern/design-pattern-decorator.md
      - Facade: design-pattern/design-pattern-facade.md
      - Flyweight: design-pattern/design-pattern-flyweight.md
      - Proxy: design-pattern/design-pattern-proxy.md
    - Behavioral Pattern:
      - Command: design-pattern/design-pattern-command.md
      - Interpreter: design-pattern/design-pattern-interpreter.md
      - Iterator: design-pattern/design-pattern-iterator.md
      - Mediator: design-pattern/design-pattern-mediator.md
      - Memento: design-pattern/design-pattern-memento.md
      - Null Object: design-pattern/design-pattern-null-object.md
      - Observer: design-pattern/design-pattern-observer.md
      - State: design-pattern/design-pattern-state.md
      - Strategy: design-pattern/design-pattern-strategy.md
      - Template Method: design-pattern/design-pattern-template-method.md
      - Visitor: design-pattern/design-pattern-visitor.md

  - Programming:
    - Development Environment:
      - Getting Started with Linux: programming/getting-started-with-linux.md
      - Getting Started with macOS: programming/getting-started-with-macos.md
    - Java Core:
      - Java Core - Basic: java/java-core-basic.md
      - Java Core - Formatting: java/java-core-formatting.md
  - Cloud:
    - Cloud Knowledge:
      - Cloud Service: cloud/cloud-service.md
    - Amazon AWS:
      - AWS Overview: cloud/aws-overview.md
      - AWS Billing Alarm: cloud/aws-billing-alarm.md
  - Tutorial:
    - Angular Tutorial:
      - Getting Started with Angular CLI: tutorial/getting-started-with-angular-cli.md
    - React Tutorial:
      - Getting Started with React: tutorial/getting-started-with-react.md
  - About: about.md

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  