site_name: Coding Geeks
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - content.code.copy

# Page tree
nav:
  - Home: index.md
  - Data Structure:
    - List: 
      - index/list/index.md
    - Linked List: data-structure/data-structure-linked-list.md
    - Stack: data-structure/data-structure-stack.md
    - Queue: data-structure/data-structure-queue.md
    - Deque: data-structure/data-structure-deque.md
    - LRU Cache: data-structure/data-structure-lru-cache.md
    - LFU Cache: data-structure/data-structure-lfu-cache.md
    - Monotonic Queue: data-structure/data-structure-monotonic-queue.md
    - Skip List: data-structure/data-structure-skip-list.md
    - Tree: 
      - index/tree/index.md
      - Binary Tree: data-structure/data-structure-binary-tree.md
      - Binary Search Tree: data-structure/data-structure-binary-search-tree.md
      - Red Black Tree: data-structure/data-structure-red-black-tree.md
      - N-ary Tree: data-structure/data-structure-nary-tree.md
      - B Tree: data-structure/data-structure-b-tree.md
      - B+ Tree: data-structure/data-structure-b-plus-tree.md
      - Trie: data-structure/data-structure-trie.md
      - Segment Tree: data-structure/data-structure-segment-tree.md
      - Fenwick Tree: data-structure/data-structure-fenwick-tree.md
    - Set and Map: 
      - index/map/index.md
      - HashMap: data-structure/data-structure-hashmap.md
      - Heap: data-structure/data-structure-heap.md
      - Bloom Filter: data-structure/data-structure-bloom-filter.md
    - Graph: 
      - index/graph/index.md
      - Graph: data-structure/data-structure-graph.md
      #- Graph Problems: data-structure/data-structure-graph-problems.md
      - Bipartite Graph: data-structure/data-structure-bipartite-graph.md
      - Directed Graph: data-structure/data-structure-directed-graph.md
      - Topological Sorting: data-structure/data-structure-topological-sorting.md
      - Minimum Spanning Tree: data-structure/data-structure-minimum-spanning-tree.md
  - Algorithm:
    - Sorting:
      - index/sorting/index.md
      - Basic Sorting Algorithms: algorithm/algorithm-sorting.md
      - Heap Sort: algorithm/algorithm-sorting.md
      - Merge Sort: algorithm/algorithm-sorting.md
      - Quick Sort: algorithm/algorithm-sorting.md
      - Bucket Sort: algorithm/algorithm-sorting.md
    - Common Algorithms:
      - index/commons/index.md
      - Binary Search: algorithm/algorithm-binary-search.md
      - Divide and Conquer: algorithm/algorithm-divide-and-conquer.md
      - BFS and DFS: algorithm/algorithm-bfs-and-dfs.md
      - Two Pointers: algorithm/algorithm-two-pointers.md
      - Combination and Permutation: algorithm/algorithm-combination-and-permutation.md
      - Union Find: algorithm/algorithm-union-find.md
    - Dynamic Programming:
      - index/dp/index.md
      - Dynamic Programming: algorithm/algorithm-dynamic-programming.md
      - Sequence DP: algorithm/algorithm-sequence-dp.md
      - Two Sequences DP: algorithm/algorithm-two-sequences-dp.md
      - Matrix DP: algorithm/algorithm-matrix-dp.md
      - Knapsack Problems: algorithm/algorithm-knapsack-problems.md
    - Others:
      - index/other/index.md
      - Sweep Line: algorithm/algorithm-sweep-line.md
      - Sqrt Decomposition: algorithm/algorithm-sqrt-decomposition.md
      - Minimax Algorithm: algorithm/algorithm-minimax-algorithm.md
      - Map Reduce: algorithm/algorithm-map-reduce.md
      - Pre Sum: algorithm/algorithm-pre-sum.md
      - Coordinate: algorithm/algorithm-coordinate.md
      - Bit Manipulation: algorithm/algorithm-bit-manipulation.md
      - Math: algorithm/algorithm-math.md
  - Programming:
    - Development Environment:
      - Getting Started with Linux: programming/getting-started-with-linux.md
      - Getting Started with macOS: programming/getting-started-with-macos.md
    - Java Core:
      - Java Core - Basic: java/java-core-basic.md
      - Java Core - Formatting: java/java-core-formatting.md
  - Cloud:
    - Cloud Knowledge:
      - Cloud Service: cloud/cloud-service.md
    - Amazon AWS:
      - AWS Overview: cloud/aws-overview.md
      - AWS Billing Alarm: cloud/aws-billing-alarm.md
  - Tutorial:
    - Angular Tutorial:
      - Getting Started with Angular CLI: tutorial/getting-started-with-angular-cli.md
    - React Tutorial:
      - Getting Started with React: tutorial/getting-started-with-react.md
  - About: about.md

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  