site_name: Coding Geeks
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy

# Page tree
nav:
  - Home: index.md
  - Algorithm:
    - Data Structure:
      - Data Structure - Linked List: algorithm/data-structure/data-structure-linked-list.md
      - Data Structure - Stack: algorithm/data-structure/data-structure-stack.md
      - Data Structure - Queue: algorithm/data-structure/data-structure-queue.md
      - Data Structure - Deque: algorithm/data-structure/data-structure-deque.md
      - Data Structure - LRU Cache: algorithm/data-structure/data-structure-lru-cache.md
      - Data Structure - LFU Cache: algorithm/data-structure/data-structure-lfu-cache.md
      - Data Structure - Monotonic Queue: algorithm/data-structure/data-structure-monotonic-queue.md
      - Data Structure - Skip List: algorithm/data-structure/data-structure-skip-list.md
      - Data Structure - Tree: algorithm/data-structure/data-structure-tree.md
      - Data Structure - Binary Search Tree: algorithm/data-structure/data-structure-binary-search-tree.md
      - Data Structure - Red Black Tree: algorithm/data-structure/data-structure-red-black-tree.md
      - Data Structure - N-ary Tree: algorithm/data-structure/data-structure-nary-tree.md
      - Data Structure - B Tree: algorithm/data-structure/data-structure-b-tree.md
      - Data Structure - B+ Tree: algorithm/data-structure/data-structure-b-plus-tree.md
      - Data Structure - Trie: algorithm/data-structure/data-structure-trie.md
      - Data Structure - Segment Tree: algorithm/data-structure/data-structure-segment-tree.md
      - Data Structure - Fenwick Tree: algorithm/data-structure/data-structure-fenwick-tree.md
      - Data Structure - HashMap: algorithm/data-structure/data-structure-hashmap.md
      - Data Structure - Heap: algorithm/data-structure/data-structure-heap.md
      - Data Structure - Bloom Filter: algorithm/data-structure/data-structure-bloom-filter.md
      - Data Structure - Graph: algorithm/data-structure/data-structure-graph.md
      - Data Structure - Graph Problems: algorithm/data-structure/data-structure-graph-problems.md
      - Data Structure - Bipartite Graph: algorithm/data-structure/data-structure-bipartite-graph.md
      - Data Structure - Directed Graph: algorithm/data-structure/data-structure-directed-graph.md
      - Data Structure - Topological Sorting: algorithm/data-structure/data-structure-topological-sorting.md
      - Data Structure - Minimum Spanning Tree: algorithm/data-structure/data-structure-minimum-spanning-tree.md
    - Algorithm:
      - Algorithm - Sorting: algorithm/algorithm/algorithm-sorting.md
      - Algorithm - Bit Manipulation: algorithm/algorithm/algorithm-bit-manipulation.md
      - Algorithm - Binary Search: algorithm/algorithm/algorithm-binary-search.md
      - Algorithm - Two Pointers: algorithm/algorithm/algorithm-two-pointers.md
      - Algorithm - Divide and Conquer: algorithm/algorithm/algorithm-divide-and-conquer.md
      - Algorithm - BFS and DFS: algorithm/algorithm/algorithm-bfs-and-dfs.md
      - Algorithm - Combination and Permutation: algorithm/algorithm/algorithm-combination-and-permutation.md
      - Algorithm - Union Find: algorithm/algorithm/algorithm-union-find.md
      - Algorithm - Dynamic Programming: algorithm/algorithm/algorithm-dynamic-programming.md
      - Algorithm - Sequence DP: algorithm/algorithm/algorithm-sequence-dp.md
      - Algorithm - Two Sequences DP: algorithm/algorithm/algorithm-two-sequences-dp.md
      - Algorithm - Matrix DP: algorithm/algorithm/algorithm-matrix-dp.md
      - Algorithm - Knapsack Problems: algorithm/algorithm/algorithm-knapsack-problems.md
      - Algorithm - Sweep Line: algorithm/algorithm/algorithm-sweep-line.md
      - Algorithm - Sqrt Decomposition: algorithm/algorithm/algorithm-sqrt-decomposition.md
      - Algorithm - Minimax Algorithm: algorithm/algorithm/algorithm-minimax-algorithm.md
      - Algorithm - Map Reduce: algorithm/algorithm/algorithm-map-reduce.md
      - Algorithm - Pre Sum: algorithm/algorithm/algorithm-pre-sum.md
      - Algorithm - Coordinate: algorithm/algorithm/algorithm-coordinate.md
      - Algorithm - Math: algorithm/algorithm/algorithm-math.md
    - Algorithm Overview: algorithm/algorithm-overview.md
  - Programming:
    - Development Environment:
      - Getting Started with Linux: programming/getting-started-with-linux.md
      - Getting Started with macOS: programming/getting-started-with-macos.md
    - Java Core:
      - Java Core - Basic: java/java-core-basic.md
      - Java Core - Formatting: java/java-core-formatting.md
  - Cloud:
    - Cloud Knowledge:
      - Cloud Service: cloud/cloud-service.md
    - Amazon AWS:
      - AWS Overview: cloud/aws-overview.md
      - AWS Billing Alarm: cloud/aws-billing-alarm.md
  - Tutorial:
    - Angular Tutorial:
      - Getting Started with Angular CLI: tutorial/getting-started-with-angular-cli.md
    - React Tutorial:
      - Getting Started with React: tutorial/getting-started-with-react.md
  - About: about.md

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  